# @package _global_

defaults:
  - /benchmark/nav/socialnav_v2: falcon_hm3d_task
  - /habitat_baselines: habitat_baselines_rl_config_base
  - /habitat/simulator/sim_sensors@habitat_baselines.eval.extra_sim_sensors.third_rgb_sensor: third_rgb_sensor 
  - /habitat_baselines/rl/policy@habitat_baselines.rl.policy.agent_1: single_fixed
  - /habitat_baselines/rl/policy@habitat_baselines.rl.policy.agent_2: single_fixed
  - /habitat_baselines/rl/policy@habitat_baselines.rl.policy.agent_3: single_fixed
  - /habitat_baselines/rl/policy@habitat_baselines.rl.policy.agent_4: single_fixed
  - /habitat_baselines/rl/policy@habitat_baselines.rl.policy.agent_5: single_fixed
  - /habitat_baselines/rl/policy@habitat_baselines.rl.policy.agent_6: single_fixed
  - /habitat/task/actions@habitat.task.actions.agent_0_discrete_stop: discrete_stop
  - /habitat/task/actions@habitat.task.actions.agent_0_discrete_move_forward: discrete_move_forward
  - /habitat/task/actions@habitat.task.actions.agent_0_discrete_turn_left: discrete_turn_left
  - /habitat/task/actions@habitat.task.actions.agent_0_discrete_turn_right: discrete_turn_right
  - /habitat/task/actions@habitat.task.actions.agent_1_oracle_nav_randcoord_action_obstacle: oracle_nav_action 
  - /habitat/task/actions@habitat.task.actions.agent_2_oracle_nav_randcoord_action_obstacle: oracle_nav_action 
  - /habitat/task/actions@habitat.task.actions.agent_3_oracle_nav_randcoord_action_obstacle: oracle_nav_action 
  - /habitat/task/actions@habitat.task.actions.agent_4_oracle_nav_randcoord_action_obstacle: oracle_nav_action 
  - /habitat/task/actions@habitat.task.actions.agent_5_oracle_nav_randcoord_action_obstacle: oracle_nav_action 
  - /habitat/task/actions@habitat.task.actions.agent_6_oracle_nav_randcoord_action_obstacle: oracle_nav_action 
  - /habitat/task/lab_sensors@habitat.task.lab_sensors.agent_0_pointgoal_with_gps_compass: pointgoal_with_gps_compass_sensor
  - _self_

habitat:
  environment:
    iterator_options:
      shuffle: False # keeps the same order
  gym:
    obs_keys:
      - agent_0_articulated_agent_jaw_depth
      - agent_0_articulated_agent_jaw_rgb
      - agent_0_pointgoal_with_gps_compass
  task:
    actions:
      agent_0_discrete_stop:
        lin_speed: 0.0 
        ang_speed: 0.0
      agent_0_discrete_move_forward:
        lin_speed: 25.0
        ang_speed: 0.0
        allow_dyn_slide: True
      agent_0_discrete_turn_left:
        lin_speed: 0.0
        ang_speed: 10.0
        allow_dyn_slide: True
      agent_0_discrete_turn_right:
        lin_speed: 0.0
        ang_speed: -10.0
        allow_dyn_slide: True
      agent_1_oracle_nav_randcoord_action_obstacle:
        type: OracleNavRandCoordAction_Obstacle 
        motion_control: human_joints
        lin_speed: 10.0
        ang_speed: 10.0
        allow_dyn_slide: True
      agent_2_oracle_nav_randcoord_action_obstacle:
        type: OracleNavRandCoordAction_Obstacle 
        motion_control: human_joints
        lin_speed: 10.0
        ang_speed: 10.0
        allow_dyn_slide: True
      agent_3_oracle_nav_randcoord_action_obstacle:
        type: OracleNavRandCoordAction_Obstacle 
        motion_control: human_joints
        lin_speed: 10.0
        ang_speed: 10.0
        allow_dyn_slide: True
      agent_4_oracle_nav_randcoord_action_obstacle:
        type: OracleNavRandCoordAction_Obstacle 
        motion_control: human_joints
        lin_speed: 10.0
        ang_speed: 10.0
        allow_dyn_slide: True
      agent_5_oracle_nav_randcoord_action_obstacle:
        type: OracleNavRandCoordAction_Obstacle 
        motion_control: human_joints
        lin_speed: 10.0
        ang_speed: 10.0
        allow_dyn_slide: True
      agent_6_oracle_nav_randcoord_action_obstacle:
        type: OracleNavRandCoordAction_Obstacle 
        motion_control: human_joints
        lin_speed: 10.0
        ang_speed: 10.0
        allow_dyn_slide: True        
habitat_baselines:
  evaluate: True
  eval_ckpt_path_dir: data/dummy_policy.pth
  num_environments: 1
  load_resume_state_config: False

  torch_gpu_id: 0
  tensorboard_dir: "tb"
  video_dir: "video_dir"
  test_episode_count: -1
  checkpoint_folder: "data/new_checkpoints"
  trainer_name: "vlfm"
  num_updates: 270000
  log_interval: 10
  num_checkpoints: 100
  # Force PyTorch to be single threaded as
  # this improves performance considerably
  force_torch_single_threaded: True

  eval:
    split: "val"

  rl:

    policy:
      name: "HabitatITMPolicyV2"

    ppo:
      # ppo params
      clip_param: 0.2
      ppo_epoch: 4
      num_mini_batch: 2
      value_loss_coef: 0.5
      entropy_coef: 0.01
      lr: 2.5e-4
      eps: 1e-5
      max_grad_norm: 0.2
      num_steps: 64
      use_gae: True
      gamma: 0.99
      tau: 0.95
      use_linear_clip_decay: False
      use_linear_lr_decay: False
      reward_window_size: 50

      use_normalized_advantage: False

      distrib_backend: NCCL #VLFM 동일
      hidden_size: 512 

    ddppo:
      sync_frac: 0.6 #VLFM 동일
      # The PyTorch distributed backend to use
      distrib_backend: NCCL #VLFM 동일
      # Visual encoder backbone
      pretrained_weights: data/ddppo-models/gibson-2plus-resnet50.pth
      # Initialize with pretrained weights
      pretrained: False #VLFM 동일 (아마 True라면 위에 모델로드하나봄.,.,)
      # Initialize just the visual encoder backbone with pretrained weights
      pretrained_encoder: False #VLFM 동일
      # Whether or not the visual encoder backbone will be trained.
      train_encoder: True #VLFM 동일
      # Whether or not to reset the critic linear layer
      reset_critic: False #VLFM 에서는 False

      # Model parameters
      backbone: resnet50 #VLFM 동일
      rnn_type: LSTM #VLFM 동일
      num_recurrent_layers: 2 #VLFM 동일